// <auto-generated />
using System;
using FitnessTracker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessTracker.Api.Migrations
{
    [DbContext(typeof(FitnessTrackerDbContext))]
    [Migration("20260929125340_AddRoutineIdToWorkouts")]
    partial class AddRoutineIdToWorkouts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FitnessTracker.Api.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MuscleGroup")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Barbell pressing exercise",
                            ImageUrl = "/assets/ExerciseImages/chestpress.jpg",
                            MuscleGroup = "Chest",
                            Name = "Bench Press"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Compound lower-body exercise",
                            ImageUrl = "/assets/ExerciseImages/squat.jpg",
                            MuscleGroup = "Legs",
                            Name = "Squat"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Cable pulling exercise",
                            ImageUrl = "/assets/ExerciseImages/latpulldown.jpg",
                            MuscleGroup = "Back",
                            Name = "Lat Pulldown"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Machine chest exercise",
                            ImageUrl = "/assets/ExerciseImages/chestfly.jpg",
                            MuscleGroup = "Chest",
                            Name = "Chest Fly"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Machine lower-body exercise",
                            ImageUrl = "/assets/ExerciseImages/legpress.jpg",
                            MuscleGroup = "Legs",
                            Name = "Leg Press"
                        });
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.Routine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Routines");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.RoutineExercise", b =>
                {
                    b.Property<int>("RoutineId")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("TargetReps")
                        .HasColumnType("int");

                    b.Property<int>("TargetSets")
                        .HasColumnType("int");

                    b.HasKey("RoutineId", "ExerciseId");

                    b.HasIndex("ExerciseId");

                    b.ToTable("RoutineExercises");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("RoutineId")
                        .HasColumnType("int");

                    b.Property<string>("RoutineName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.WorkoutSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ExercisePosition")
                        .HasColumnType("int");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<int>("SetNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId");

                    b.ToTable("WorkoutSets");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.RoutineExercise", b =>
                {
                    b.HasOne("FitnessTracker.Api.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessTracker.Api.Models.Routine", "Routine")
                        .WithMany("RoutineExercises")
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Routine");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.WorkoutSet", b =>
                {
                    b.HasOne("FitnessTracker.Api.Models.Workout", "Workout")
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.Routine", b =>
                {
                    b.Navigation("RoutineExercises");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.Workout", b =>
                {
                    b.Navigation("Sets");
                });
#pragma warning restore 612, 618
        }
    }
}
